### PR TITLE
Fix issue #27 and #16 (Implement getVoxels and setVoxels)

### LINKED ISSUE #16: Unnecessary type conversion when wrapping to ImagePlus
Consider the following Groovy script:
```groovy
#@ DatasetIOService datasetIO
#@ UIService ui
bigCellImg = datasetIO.open("big&pixelType=uint8&axes=X,Y,Z,Time&lengths=3000,4000,5000,6000.fake")
ui.show(bigCellImg)
```
This pops up the huge image very quickly, which is awesome.

But now put a breakpoint at `org.scijava.ui.DefaultUIService` line 381 of `org.scijava:scijava-common:2.73.1`; this will be the line `ui.show(display)` inside `onEvent(DisplayCreated)`. Run the same script above, and it will break there. Then STEP instead of CONTINUE. The step now hangs, with `IterableIntervalProjector2D.map` taking forever to complete. (I waited minutes, and it still was not done.)

Here are some example stack traces of what is going on during the step, retrieved from the CLI using <kbd>ctrl</kbd>+<kbd>\\</kbd>:
```
"AWT-EventQueue-0" #21 prio=6 os_prio=31 tid=0x00007fd158950000 nid=0x6e23 runnable [0x00007000066d7000]
   java.lang.Thread.State: RUNNABLE
	at net.imglib2.type.numeric.integer.UnsignedByteType.get(UnsignedByteType.java:151)
	at net.imglib2.type.numeric.integer.UnsignedByteType.getIntegerLong(UnsignedByteType.java:168)
	at net.imglib2.type.numeric.integer.AbstractIntegerType.getRealDouble(AbstractIntegerType.java:62)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:79)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:72)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixels(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:85)
	at ij.ImagePlus.setStack(ImagePlus.java:683)
	at ij.ImagePlus.<init>(ImagePlus.java:154)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:100)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:80)
	at net.imagej.legacy.translate.ImagePlusCreator.createImagePlus(ImagePlusCreator.java:121)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:98)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:87)
	at net.imagej.legacy.translate.ImageTranslator.createLegacyImage(ImageTranslator.java:74)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:267)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:254)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:121)
	at org.scijava.ui.viewer.DisplayViewer.view(DisplayViewer.java:86)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:114)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:381)

"AWT-EventQueue-0" #21 prio=6 os_prio=31 tid=0x00007fd158950000 nid=0x6e23 runnable [0x00007000066d7000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Double.doubleToRawLongBits(Native Method)
	at java.lang.Math.copySign(Math.java:1766)
	at java.lang.Math.signum(Math.java:1525)
	at net.imglib2.util.Util.round(Util.java:499)
	at net.imglib2.type.numeric.integer.AbstractIntegerType.setReal(AbstractIntegerType.java:74)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:84)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:72)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixels(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:85)
	at ij.ImagePlus.setStack(ImagePlus.java:683)
	at ij.ImagePlus.<init>(ImagePlus.java:154)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:100)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:80)
	at net.imagej.legacy.translate.ImagePlusCreator.createImagePlus(ImagePlusCreator.java:121)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:98)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:87)
	at net.imagej.legacy.translate.ImageTranslator.createLegacyImage(ImageTranslator.java:74)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:267)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:254)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:121)
	at org.scijava.ui.viewer.DisplayViewer.view(DisplayViewer.java:86)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:114)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:381)

"AWT-EventQueue-0" #16 prio=6 os_prio=31 tid=0x00007fb4c4388000 nid=0xda27 runnable [0x000070000dc18000]
   java.lang.Thread.State: RUNNABLE
	at net.imglib2.view.MixedRandomAccess.get(MixedRandomAccess.java:364)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixels(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:85)
	at ij.ImagePlus.setStack(ImagePlus.java:683)
	at ij.ImagePlus.<init>(ImagePlus.java:154)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:100)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:80)
	at net.imagej.legacy.translate.ImagePlusCreator.createImagePlus(ImagePlusCreator.java:121)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:98)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:87)
	at net.imagej.legacy.translate.ImageTranslator.createLegacyImage(ImageTranslator.java:74)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:267)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:254)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:121)
	at org.scijava.ui.viewer.DisplayViewer.view(DisplayViewer.java:86)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:114)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:381)

"AWT-EventQueue-0" #16 prio=6 os_prio=31 tid=0x00007fb4c4388000 nid=0xda27 runnable [0x000070000dc18000]
   java.lang.Thread.State: RUNNABLE
	at net.imglib2.img.array.AbstractArrayCursor.get(AbstractArrayCursor.java:123)
	at net.imglib2.img.array.AbstractArrayCursor.get(AbstractArrayCursor.java:53)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixels(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:85)
	at ij.ImagePlus.setStack(ImagePlus.java:683)
	at ij.ImagePlus.<init>(ImagePlus.java:154)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:100)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:80)
	at net.imagej.legacy.translate.ImagePlusCreator.createImagePlus(ImagePlusCreator.java:121)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:98)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:87)
	at net.imagej.legacy.translate.ImageTranslator.createLegacyImage(ImageTranslator.java:74)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:267)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:254)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:121)
	at org.scijava.ui.viewer.DisplayViewer.view(DisplayViewer.java:86)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:114)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:381)


"AWT-EventQueue-0" #16 prio=6 os_prio=31 tid=0x00007fb4c4388000 nid=0xda27 runnable [0x000070000dc18000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.Math.signum(Math.java:1525)
	at net.imglib2.util.Util.round(Util.java:499)
	at net.imglib2.type.numeric.integer.AbstractIntegerType.setReal(AbstractIntegerType.java:74)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:84)
	at net.imglib2.img.display.imagej.ImageJVirtualStackUnsignedByte$ByteConverter.convert(ImageJVirtualStackUnsignedByte.java:72)
	at net.imglib2.display.projector.IterableIntervalProjector2D.map(IterableIntervalProjector2D.java:151)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getSlice(ImageJVirtualStack.java:148)
	at net.imglib2.img.display.imagej.ImageJVirtualStack.getPixels(ImageJVirtualStack.java:155)
	at net.imglib2.img.display.imagej.AbstractVirtualStack.getProcessor(AbstractVirtualStack.java:85)
	at ij.ImagePlus.setStack(ImagePlus.java:683)
	at ij.ImagePlus.<init>(ImagePlus.java:154)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:100)
	at net.imglib2.img.display.imagej.ImgToVirtualStack.wrap(ImgToVirtualStack.java:80)
	at net.imagej.legacy.translate.ImagePlusCreator.createImagePlus(ImagePlusCreator.java:121)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:98)
	at net.imagej.legacy.translate.ImagePlusCreator.createLegacyImage(ImagePlusCreator.java:87)
	at net.imagej.legacy.translate.ImageTranslator.createLegacyImage(ImageTranslator.java:74)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:267)
	at net.imagej.legacy.LegacyImageMap.registerDisplay(LegacyImageMap.java:254)
	at net.imagej.legacy.display.LegacyImageDisplayViewer.view(LegacyImageDisplayViewer.java:121)
	at org.scijava.ui.viewer.DisplayViewer.view(DisplayViewer.java:86)
	at net.imagej.legacy.ui.LegacyUI$1.run(LegacyUI.java:197)
	at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:114)
	at net.imagej.legacy.ui.LegacyUI.show(LegacyUI.java:193)
	at org.scijava.ui.DefaultUIService.onEvent(DefaultUIService.java:381)
```

The gist is that `IterableIntervalProjector2D.map` uses a `ImageJVirtualStackUnsignedByte$ByteConverter` to do an identity conversion from `UnsignedByteType` to `UnsignedByteType`—i.e. no value adjustment. I am guessing that when stepping in the debugger, we do not gain the full benefits of JIT/inlining, so end up looping over all samples. Even then, it seems odd it is so slow... but regardless, this code path is highly suboptimal. Would be much better not to use the converter at all in circumstances where the source type already matches.

### PR DESCRIPTION
**Pull request by maarzt**
This PR fixes issue #27.

That means ImageJVirtualStack now implement getVoxels and setVoxels.

Additionally:
* A bug when using AbstractVirtualStack with ColorProcessor is fixed.
* Pixel type conversion in ImageJVirtualStack is cleaned up, this fixes #16. Previously ImageJVirtualStack used Converters. Which was very tricky because this only worked for reading but ImageJVirtualStack also supports writing. Now SamplerConverters are used instead.

### CODE REVIEW

File: src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java [hunk 1]
```diff
@@ -34,65 +34,68 @@
...
 		assert source.numDimensions() > 1;
 		this.source = zeroMin( source );
+		this.type = Util.getTypeFromInterval( source );
 		this.higherSourceDimensions = initHigherDimensions( source );
-		this.type = type;
-		this.converter = converter;
-		this.service = service;
 	}
 
 	private static int multiply( final long[] higherSourceDimensions )
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java]: This method can be removed. Use `Intervals.numElements( long... )` instead

File: src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java [hunk 2]
```diff
@@ -112,6 +115,11 @@ private static int multiply( final long[] higherSourceDimensions )
 		return Views.isZeroMin( source ) ? source : Views.zeroMin( source );
 	}
 
+	public void setExecuterService( ExecutorService service )
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java]: typo: should be setExecut**o**rService

File: src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java [hunk 3]
```diff
@@ -34,65 +34,68 @@
...
+import java.util.stream.IntStream;
+import java.util.stream.LongStream;
+
 /**
  * TODO
  *
  */
 public class ImageJVirtualStack< S, T extends NativeType< T > > extends AbstractVirtualStack
 {
+
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java]: generic parameter `S` can be removed from class, moved to constructor instead

File: src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java [hunk 4]
```diff
@@ -135,18 +143,28 @@ public boolean isWritable()
...
+	private void project( int index, Img< T > img, Converter< T, T > converter )
+	{
 		final AbstractProjector2D projector = ( service == null )
 				? new IterableIntervalProjector2D<>( 0, 1, source, img, converter )
 				: new MultithreadedIterableIntervalProjector2D<>( 0, 1, source, img, converter, service );
+		setPostition( index, projector );
+		projector.map();
+	}
+
+	private void setPostition( int index, Positionable projector )
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java]: typo: should be setPosition

**Comment by tpietzsch** [comment]
please format with imglib2 code style

File: src/main/java/net/imglib2/img/display/imagej/ImageProcessorUtils.java [hunk 5]
```diff
@@ -73,4 +75,17 @@ public static boolean isSupported( final Type< ? > type )
 		return ( type instanceof UnsignedByteType ) || ( type instanceof UnsignedShortType ) ||
 				( type instanceof ARGBType ) || ( type instanceof FloatType );
 	}
+
+	public static Img< ? > initArrayImg( final int sizeX, final int sizeY, final Object pixels )
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/ImageProcessorUtils.java]: Please add javadoc (not clear from the signatory that `Object pixels` means primitive type array).

(I know that "no javadoc" keeps with the theme of existing imglib2-ij code. But let's try to improve this situation.)

File: src/main/java/net/imglib2/img/display/imagej/AbstractVirtualStack.java [hunk 6]
```diff
@@ -340,27 +358,86 @@ public String toString()
...
+				(BiConsumer< RealType, FloatType >) (o, i) -> o.setReal( i.getRealFloat() ) :
+				(BiConsumer< RealType, FloatType >) (i, o) -> o.setReal( i.getRealFloat() );
+	}
+
+	private static BiConsumer<ARGBType, FloatType> arbgVoxelAccessAction( Integer channel, boolean isSetVoxel )
+	{
+		if( channel == null )
+			return isSetVoxel ?
+					( o, i ) -> o.set( (int) i.getRealFloat() ) :
+					( i, o ) -> o.set( i.get() );
```
Comment (tpietzsch) [inline src/main/java/net/imglib2/img/display/imagej/AbstractVirtualStack.java]: I would find this more readable, if variables are renamed like
```java
return isSetVoxel ?
		( a, b ) -> a.set( ( int ) b.getRealFloat() ) :
		( a, b ) -> b.set( a.get() );
```
I can mentally assign "Ok, `a` that's the ARGBType, and `b` that's the `FloatType`" and then I parse the lines.
Using suggestive names ('i' "input", `o` "output") and then flipping the order is much more confusing (at least to me).

**Comment by tpietzsch** [comment]
I made some inline comments.

In general, I would really, really, *really* appreciate it, if you add/fix javadoc while you make changes to the code.

In particular, now that the `ImageJVirtualStack` sometimes is read-only (swallowing writes) and sometimes write-through, I found it super-difficult to dig back through the layers from the various `BdvFunctions.show(...)`, `BdvFunctions.wrap(...)` variants to find out in which case what happens. A little bit of documentation would go a long way there.

**Comment by tpietzsch** [comment]
> please format with imglib2 code style

Also make variables final if possible

File: src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java (hunk 1 above)
Comment (maarzt) [reply src/main/java/net/imglib2/img/display/imagej/ImageJVirtualStack.java]: No it cannot be remove by `Intervals.numElements( long... )` because for an empty array numElements crashes, while `multiply` returns `1`. We could fix `Intervals.numElements(long ...)` to return `1` for an empty array?

**Comment by maarzt** [comment]
@tpietzsch We need to finish this PR rather soon. People stumble across the issues, that are fixed here.
